[2025-04-23T14:33:56.874+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:33:56.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T14:33:56.895+0000] {logging_mixin.py:190} INFO - [2025-04-23T14:33:56.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:33:56.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:33:56.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.081 seconds
[2025-04-23T14:34:27.210+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:34:27.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T14:34:27.735+0000] {logging_mixin.py:190} INFO - [2025-04-23T14:34:27.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:34:27.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:34:27.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.557 seconds
[2025-04-23T14:34:58.488+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:34:58.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T14:34:58.493+0000] {logging_mixin.py:190} INFO - [2025-04-23T14:34:58.493+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:34:58.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T14:34:58.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.048 seconds
[2025-04-23T16:31:46.961+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:31:46.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:31:47.022+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:31:47.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:31:47.096+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:31:47.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 62
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 57
[2025-04-23T16:31:47.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:31:47.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.546 seconds
[2025-04-23T16:32:17.584+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:32:17.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:32:17.593+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:32:17.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:32:17.604+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:32:17.601+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 62
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 57
[2025-04-23T16:32:17.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:32:17.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.084 seconds
[2025-04-23T16:32:47.869+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:32:47.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:32:47.880+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:32:47.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:32:47.893+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:32:47.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 62
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 57
[2025-04-23T16:32:47.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:32:47.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.065 seconds
[2025-04-23T16:33:18.393+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:33:18.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:33:18.410+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:33:18.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:33:18.420+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:33:18.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 62
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 57
[2025-04-23T16:33:18.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:33:18.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.060 seconds
[2025-04-23T16:33:48.838+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:33:48.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:33:48.853+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:33:48.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:33:48.863+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:33:48.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 62
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 57
[2025-04-23T16:33:48.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:33:48.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.080 seconds
[2025-04-23T16:34:19.191+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:19.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:34:19.198+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:34:19.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:19.211+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:34:19.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 62
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 57
[2025-04-23T16:34:19.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:19.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.081 seconds
[2025-04-23T16:34:21.220+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:21.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:34:21.225+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:34:21.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:21.233+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:34:21.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:34:21.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:21.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.036 seconds
[2025-04-23T16:34:52.031+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:52.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:34:52.052+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:34:52.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:52.078+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:34:52.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:34:52.079+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:34:52.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.117 seconds
[2025-04-23T16:35:22.654+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:35:22.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:35:22.662+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:35:22.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:35:22.673+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:35:22.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:35:22.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:35:22.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.086 seconds
[2025-04-23T16:35:52.956+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:35:52.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:35:52.976+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:35:52.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:35:52.987+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:35:52.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:35:52.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:35:53.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.136 seconds
[2025-04-23T16:36:23.381+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:36:23.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:36:23.390+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:36:23.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:36:23.400+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:36:23.397+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:36:23.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:36:23.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.095 seconds
[2025-04-23T16:36:54.018+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:36:54.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:36:54.039+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:36:54.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:36:54.049+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:36:54.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:36:54.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:36:54.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.083 seconds
[2025-04-23T16:37:24.453+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:37:24.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:37:24.464+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:37:24.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:37:24.475+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:37:24.473+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:37:24.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:37:24.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.092 seconds
[2025-04-23T16:37:54.942+0000] {processor.py:186} INFO - Started process (PID=221) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:37:54.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:37:54.949+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:37:54.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:37:54.956+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:37:54.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:37:54.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:37:54.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.052 seconds
[2025-04-23T16:38:25.257+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:38:25.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:38:25.264+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:38:25.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:38:25.269+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:38:25.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:38:25.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:38:25.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.043 seconds
[2025-04-23T16:38:55.885+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:38:55.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:38:55.940+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:38:55.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:38:56.012+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:38:56.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:38:56.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:38:56.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.290 seconds
[2025-04-23T16:39:26.374+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:39:26.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:39:26.384+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:39:26.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:39:26.393+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:39:26.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:39:26.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:39:26.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.083 seconds
[2025-04-23T16:39:56.927+0000] {processor.py:186} INFO - Started process (PID=249) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:39:56.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:39:56.938+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:39:56.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:39:56.952+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:39:56.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:39:56.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:39:57.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.131 seconds
[2025-04-23T16:40:06.096+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:40:06.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:40:06.107+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:40:06.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:40:06.137+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:40:06.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:40:06.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:40:06.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.090 seconds
[2025-04-23T16:40:36.489+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:40:36.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:40:36.495+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:40:36.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:40:36.507+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:40:36.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:40:36.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:40:36.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.051 seconds
[2025-04-23T16:41:01.880+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:41:01.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:41:01.886+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:41:01.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:41:01.905+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:41:01.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:41:01.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:41:01.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.088 seconds
[2025-04-23T16:41:32.553+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:41:32.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:41:32.567+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:41:32.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:41:32.593+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:41:32.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:41:32.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:41:32.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.130 seconds
[2025-04-23T16:42:03.326+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:03.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:42:03.334+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:42:03.333+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:03.345+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:42:03.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:42:03.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:03.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.059 seconds
[2025-04-23T16:42:33.979+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:33.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:42:33.986+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:42:33.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:34.009+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:42:34.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 30, in <module>
    JOB_FLOW_OVERRIDES: dict[str, Any] = {
                                  ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
[2025-04-23T16:42:34.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:34.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.072 seconds
[2025-04-23T16:42:50.937+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:50.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:42:50.948+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:42:50.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:50.960+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:42:50.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 60, in <module>
    start_date=datetime(2025, 4, 23),
               ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
[2025-04-23T16:42:50.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:42:50.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.070 seconds
[2025-04-23T16:43:21.513+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:43:21.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:43:21.529+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:21.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:43:21.541+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:21.538+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/emr-orchestration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/emr-orchestration.py", line 60, in <module>
    start_date=datetime(2025, 4, 23),
               ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
[2025-04-23T16:43:21.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:43:21.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 0.065 seconds
[2025-04-23T16:43:38.972+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:43:38.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/emr-orchestration.py for tasks to queue
[2025-04-23T16:43:38.989+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:38.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:43:39.127+0000] {processor.py:925} INFO - DAG(s) 'emr_orchestration' retrieved from /opt/airflow/dags/emr-orchestration.py
[2025-04-23T16:43:39.890+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.890+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:emr_orchestration
[2025-04-23T16:43:39.898+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.898+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:emr_orchestration
[2025-04-23T16:43:39.904+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.903+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:emr_orchestration
[2025-04-23T16:43:39.907+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.907+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:emr_orchestration
[2025-04-23T16:43:39.911+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.911+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:emr_orchestration
[2025-04-23T16:43:39.915+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.914+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:emr_orchestration
[2025-04-23T16:43:39.918+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.918+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:emr_orchestration
[2025-04-23T16:43:39.918+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.918+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-23T16:43:39.945+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.944+0000] {dag.py:3262} INFO - Creating ORM DAG for emr_orchestration
[2025-04-23T16:43:39.964+0000] {logging_mixin.py:190} INFO - [2025-04-23T16:43:39.964+0000] {dag.py:4180} INFO - Setting next_dagrun for emr_orchestration to 2025-04-23 00:00:00+00:00, run_after=2025-04-24 00:00:00+00:00
[2025-04-23T16:43:39.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/emr-orchestration.py took 1.054 seconds
